package pretend;

public class TsecWAF {
    private static String Html;
    private static String Code;

    public static String GetHtml(){

        Html = "PCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9ImVuIj4KCjxoZWFkPgogICAgPG1ldGEgY2hhcnNldD0iVVRGLTgiPgogICAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xLjAiPgogICAgPHRpdGxlPkNsaWVudCBCYWQgUmVxdWVzdDwvdGl0bGU+CiAgICA8bGluayByZWw9InN0eWxlc2hlZXQiIGhyZWY9Imh0dHBzOi8vaW1nY2FjaGUucXEuY29tL3FjbG91ZC9zZWN1cml0eS9zdGF0aWMvNDA0c3R5bGUuY3NzIj4KPC9oZWFkPgoKPGJvZHk+CiAgICA8ZGl2IGNsYXNzPSJjb25lbnQiPgogICAgICAgIDxkaXYgY2xhc3M9ImNsaWVudFN2ZyI+CiAgICAgICAgICAgIDxpbWcgc3JjPSJodHRwczovL2ltZ2NhY2hlLnFxLmNvbS9xY2xvdWQvc2VjdXJpdHkvc3RhdGljL2ltZ3MvY2xpZW50RXJyLnN2ZyIgYWx0PSIiPgogICAgICAgIDwvZGl2PgogICAgICAgIDxoMSBjbGFzcz0iZXJyIj7lvojmirHmrYnvvIzmgqjmj5DkuqTnmoTor7fmsYLlrZjlnKjlvILluLjvvIzor7flkJHnvZHnq5nnrqHnkIblkZjnoa7orqTlubbojrflj5bmraPnoa7nmoTorr/pl67mlrnlvI88L2gxPgogICAgICAgIDxwIGNsYXNzPSJ0ZXh0MSI+5pys6aG16Z2i5Li6PHNwYW4gY2xhc3M9InRleHQtY29sb3IiPuiFvuiur1QtU2VjIFdlYuW6lOeUqOmYsueBq+WimShXQUYpPC9zcGFuPum7mOiupOaPkOekuumhtemdou+8jOWmguacieeWkemXruivt+iBlOezu+e9keermeeuoeeQhuWRmDwvcD4KICAgIDwvZGl2Pgo8L2JvZHk+Cgo8L2h0bWw+Cg==";
        return Html;
    }
    public static String getCode(){
        Code = "400";
        return Code;
    }
}
